"""added two new field to user table(about_me and last_seen)

Revision ID: 7330a50d60ff
Revises: 92b4f7a8cd0a
Create Date: 2020-06-02 22:44:38.514103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7330a50d60ff'
down_revision = '92b4f7a8cd0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
